//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductoPorProveedor
    {
        public int IdProducto { get; set; }
        public string EAN { get; set; }
        public string Nombre { get; set; }
        public decimal Precio { get; set; }
        public string Estado { get; set; }
        public int IdProveedor { get; set; }
        public string NombreProveedor { get; set; }
        public string EstadoProveedor { get; set; }
    }
}
