//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaveWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Ventas
    {
        public int IdVenta { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string EstadoVenta { get; set; }
        public int IdCaja { get; set; }
        public Nullable<decimal> Dinero { get; set; }
        public Nullable<System.DateTime> UltimoCierre { get; set; }
        public string EstadoCaja { get; set; }
        public int IdSucursal { get; set; }
        public string NombreSucursal { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string EstadoSucursal { get; set; }
        public int IdCliente { get; set; }
        public string Cedula { get; set; }
        public string NombreCliente { get; set; }
        public string Apellidos { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string EstadoCliente { get; set; }
    }
}
