USE PosPF
SELECT * FROM CAJA
SELECT * FROM CAJA_POR_SUCURSAL
SELECT * FROM PROVEEDOR
SELECT * FROM EMPLEADO;
SELECT * FROM SUCURSAL;
SELECT * FROM ROL;
SELECT * FROM PROVEEDOR;
SELECT * FROM EMPLEADO_POR_ROL;
SELECT * FROM CLIENTE;
SELECT * FROM PRODUCTO;
SELECT * FROM PRODUCTO_POR_PROVEEDOR;
SELECT * FROM PRODUCTO_POR_SUCURSAL;
SELECT * FROM VENTA;
SELECT * FROM VENTA_POR_CAJA;
SELECT * FROM VENTA_POR_CLIENTE;

SELECT * FROM View_Ventas
SELECT * FROM View_ProductoPorVenta